// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoKlubAPI.Models;

namespace VideoKlubAPI.Migrations
{
    [DbContext(typeof(VideoKlubContext))]
    partial class VideoKlubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VideoKlubAPI.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GodIzlaska")
                        .HasColumnType("int")
                        .HasColumnName("GodIzlaska");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int")
                        .HasColumnName("Kolicina");

                    b.Property<string>("NazivFilma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NazivFilma");

                    b.Property<int?>("OdeljenjeID")
                        .HasColumnType("int");

                    b.Property<int>("PoZURedu")
                        .HasColumnType("int")
                        .HasColumnName("PozURedu");

                    b.Property<int>("Red")
                        .HasColumnType("int")
                        .HasColumnName("Red");

                    b.Property<string>("Reziser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Reziser");

                    b.Property<string>("Trajanje")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Trajanje");

                    b.HasKey("ID");

                    b.HasIndex("OdeljenjeID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.Odeljenje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojPolicaPoRedu")
                        .HasColumnType("int")
                        .HasColumnName("BrojPolicaPoRedu");

                    b.Property<int>("BrojRedova")
                        .HasColumnType("int")
                        .HasColumnName("BrojRedova");

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.ToTable("Odeljenje");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.VideoKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("VideoKlub");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.Film", b =>
                {
                    b.HasOne("VideoKlubAPI.Models.Odeljenje", "Odeljenje")
                        .WithMany("Filmovi")
                        .HasForeignKey("OdeljenjeID");

                    b.Navigation("Odeljenje");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.Odeljenje", b =>
                {
                    b.HasOne("VideoKlubAPI.Models.VideoKlub", "Klub")
                        .WithMany("Odeljenja")
                        .HasForeignKey("KlubID");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.Odeljenje", b =>
                {
                    b.Navigation("Filmovi");
                });

            modelBuilder.Entity("VideoKlubAPI.Models.VideoKlub", b =>
                {
                    b.Navigation("Odeljenja");
                });
#pragma warning restore 612, 618
        }
    }
}
